#!/usr/bin/env bash
#Write a bash script htat gives you information about the school file

if [ -e "school" ]
then
	echo "school file exist"
	if [ -s "school" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "school" ]
	then
		echo "school is a regular file"
	fi
else
	echo "schools file does not exist"
fi
